import RPi.GPIO as GPIO
from time import sleep
from datetime import datetime

LEDa=2
LEDb=3
LEDc=4
LEDd=14
LEDe=15
LEDf=18
LEDg=17
LEDh=27
LEDi=22
LEDj=23
LEDk=24
LEDl=10
LEDm=9
LEDn=11
LEDo=25
LEDp=8
LEDq=7
LEDr=5
LEDs=6
LEDt=13


GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDa, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDb, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDc, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDd, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDe, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDf, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDg, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDh, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDi, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDj, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDk, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDl, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDm, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDn, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDo, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDp, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDq, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDr, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDs, GPIO.OUT)
GPIO.setmode(GPIO.BCM)
GPIO.setup(LEDt, GPIO.OUT)

GPIO.setwarnings(False)



for i in range(10000000):
    GPIO.output(LEDa, True)
    sleep(0.1)
    GPIO.output(LEDa, False)
    GPIO.output(LEDb, True)
    sleep(0.1)
    GPIO.output(LEDb, False)
    GPIO.output(LEDc, True)
    sleep(0.1)
    GPIO.output(LEDc, False)
    GPIO.output(LEDd, True)
    sleep(0.1)
    GPIO.output(LEDd, False)
    GPIO.output(LEDe, True)
    sleep(0.1)
    GPIO.output(LEDe, False)
    GPIO.output(LEDf, True)
    sleep(0.1)
    GPIO.output(LEDf, False)
    GPIO.output(LEDg, True)
    sleep(0.1)
    GPIO.output(LEDg, False)
    GPIO.output(LEDh, True)
    sleep(0.1)
    GPIO.output(LEDh, False)
    GPIO.output(LEDi, True)
    sleep(0.1)
    GPIO.output(LEDi, False)
    GPIO.output(LEDj, True)
    sleep(0.1)
    GPIO.output(LEDj, False)
    GPIO.output(LEDk, True)
    sleep(0.1)
    GPIO.output(LEDk, False)
    GPIO.output(LEDl, True)
    sleep(0.1)
    GPIO.output(LEDl, False)
    GPIO.output(LEDm, True)
    sleep(0.1)
    GPIO.output(LEDm, False)
    GPIO.output(LEDn, True)
    sleep(0.1)
    GPIO.output(LEDn, False)
    GPIO.output(LEDo, True)
    sleep(0.1)
    GPIO.output(LEDo, False)
    GPIO.output(LEDp, True)
    sleep(0.1)
    GPIO.output(LEDp, False)
    GPIO.output(LEDq, True)
    sleep(0.1)
    GPIO.output(LEDq, False)
    GPIO.output(LEDr, True)
    sleep(0.1)
    GPIO.output(LEDr, False)
    GPIO.output(LEDs, True)
    sleep(0.1)
    GPIO.output(LEDs, False)
    GPIO.output(LEDt, True)
    sleep(0.1)
    GPIO.output(LEDt, False)
    GPIO.output(LEDs, True)
    sleep(0.1)
    GPIO.output(LEDs, False)
    GPIO.output(LEDr, True)
    sleep(0.1)
    GPIO.output(LEDr, False)
    GPIO.output(LEDq, True)
    sleep(0.1)
    GPIO.output(LEDq, False)
    GPIO.output(LEDp, True)
    sleep(0.1)
    GPIO.output(LEDp, False)
    GPIO.output(LEDo, True)
    sleep(0.1)
    GPIO.output(LEDo, False)
    GPIO.output(LEDn, True)
    sleep(0.1)
    GPIO.output(LEDn, False)
    GPIO.output(LEDm, True)
    sleep(0.1)
    GPIO.output(LEDm, False)
    GPIO.output(LEDl, True)
    sleep(0.1)
    GPIO.output(LEDl, False)
    GPIO.output(LEDk, True)
    sleep(0.1)
    GPIO.output(LEDk, False)
    GPIO.output(LEDj, True)
    sleep(0.1)
    GPIO.output(LEDj, False)
    GPIO.output(LEDi, True)
    sleep(0.1)
    GPIO.output(LEDi, False)
    GPIO.output(LEDh, True)
    sleep(0.1)
    GPIO.output(LEDh, False)
    GPIO.output(LEDg, True)
    sleep(0.1)
    GPIO.output(LEDg, False)
    GPIO.output(LEDf, True)
    sleep(0.1)
    GPIO.output(LEDf, False)
    GPIO.output(LEDe, True)
    sleep(0.1)
    GPIO.output(LEDe, False)
    GPIO.output(LEDd, True)
    sleep(0.1)
    GPIO.output(LEDd, False)
    GPIO.output(LEDc, True)
    sleep(0.1)
    GPIO.output(LEDc, False)
    GPIO.output(LEDb, True)
    sleep(0.1)
    GPIO.output(LEDb, False)